-- =============================================================================
-- MCA Placement DB Schema
-- Clean complete schema for fresh initialization
-- =============================================================================

-- ── Core tables ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "users" (
  "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"                varchar,
  "college_email_id"    varchar UNIQUE,
  "personal_email_id"   varchar UNIQUE,
  "phone_number"        varchar,
  "aadhar"              VARCHAR,
  "linkedIn"            varchar,
  "gitHub"              varchar,
  "usn"                 varchar,
  "google_id"           varchar,
  "ug_cgpa"             float,
  "first_sem_sgpa"      float,
  "tenth_marks"         float,
  "twelfth_marks"       float,
  "resume_url"          text,
  "profile_picture_url" text,
  "verified"            boolean,
  "unlock_requested"    boolean DEFAULT false,
  "created_at"          timestamp
);

CREATE TABLE IF NOT EXISTS "spc_accounts" (
  "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"      int,
  "spc_username" varchar UNIQUE,
  "password"     varchar
);

CREATE TABLE IF NOT EXISTS "companies" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"            varchar,
  "min_cgpa"        float,
  "stipend"         varchar,
  "package"         varchar,
  "test_date"       date,
  "interview_date"  date,
  "deadline"        timestamp,
  "created_by"      int,
  "status"          varchar DEFAULT 'ongoing',
  "consent_blocked" boolean DEFAULT false,
  "tracker_blocked" boolean DEFAULT false,
  "created_at"      timestamp
);

CREATE TABLE IF NOT EXISTS "applications" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "company_id" int,
  "consent"    boolean,
  "tracker"    boolean
);

CREATE TABLE IF NOT EXISTS "forms" (
  "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"               varchar,
  "type"                varchar,
  "company_id"          int,
  "created_by"          int,
  "created_at"          timestamp,
  "accepting_responses" boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS "form_questions" (
  "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" varchar,
  "field_type"    varchar
);

CREATE TABLE IF NOT EXISTS "form_question_map" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id"     int,
  "question_id" int,
  "is_required" boolean
);

CREATE TABLE IF NOT EXISTS "form_responses" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id"     int,
  "student_id"  int,
  "company_id"  int,
  "question_id" int,
  "answer"      text
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id"       int NOT NULL,
  "message_text"    text,
  "attachment_url"  text,
  "attachment_name" text,
  "parent_id"       int,
  "created_at"      timestamp DEFAULT NOW(),
  "updated_at"      timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "mentions" (
  "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id"        int NOT NULL,
  "mentioned_user_id" int NOT NULL,
  CONSTRAINT "uq_mention" UNIQUE ("message_id", "mentioned_user_id")
);

CREATE TABLE IF NOT EXISTS "notification_subscriptions" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"         int NOT NULL,
  "endpoint"        text NOT NULL UNIQUE,
  "subscription"    jsonb NOT NULL,
  "expiration_time" bigint,
  "created_at"      timestamp DEFAULT NOW(),
  "updated_at"      timestamp DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS "idx_messages_created_at"  ON "messages" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_mentions_message_id"  ON "mentions" ("message_id");
CREATE INDEX IF NOT EXISTS "idx_notification_subscriptions_user_id" ON "notification_subscriptions" ("user_id");

-- ── Column migrations (idempotent — safe to re-run) ────────────────────────────
-- Adds columns that were introduced after the initial schema was deployed.

ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "consent_blocked" boolean DEFAULT false;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "tracker_blocked" boolean DEFAULT false;
ALTER TABLE "forms" ADD COLUMN IF NOT EXISTS "accepting_responses" boolean DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "unlock_requested" boolean DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "profile_picture_url" text;

-- ── Foreign keys (idempotent — safe to re-run on existing DB) ─────────────────

DO $$ BEGIN ALTER TABLE "spc_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "companies" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "applications" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "applications" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "forms" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "forms" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "form_question_map" ADD FOREIGN KEY ("form_id") REFERENCES "forms" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "form_question_map" ADD FOREIGN KEY ("question_id") REFERENCES "form_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "form_responses" ADD FOREIGN KEY ("form_id") REFERENCES "forms" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "form_responses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "form_responses" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "form_responses" ADD FOREIGN KEY ("question_id") REFERENCES "form_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "messages" ADD CONSTRAINT "fk_messages_parent_id" FOREIGN KEY ("parent_id") REFERENCES "messages" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "mentions" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "mentions" ADD FOREIGN KEY ("mentioned_user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "notification_subscriptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
